# Generated by Django 2.1.3 on 2018-11-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='reaction_type',
            field=models.CharField(choices=[('L', 'Laugh'), ('S', 'Sad'), ('A', 'Angry'), ('H', 'Happy')], max_length=20),
        ),
    ]
